### PR TITLE
MachO: Added stream support and ability to continue parsing when exceptions found

### PR DESCRIPTION
**Pull request by kweinmeister**
* Additional Stream interface provided, for more ways to interact with ELFsharp beyond files directly.
* Option to not throw exceptions and store them in an Exceptions array. This enables parsing as much information as possible out of files that have invalid structures, but may still be executable.
* Additional unit test added to check Exceptions array. All existing unit tests pass.

### CODE REVIEW

**Comment by konrad-kruczynski** [comment]
Unfortunately I did not manage to do it on Sunday, but I still remember about the PR and will check it ;) From the quick remarks I can put here now: what do you think about adding a test for some malformed MachO binary that will trigger an exception (or rather: trigger it internally but parse what could be parsed).

**Comment by kweinmeister** [comment]
That is a good idea @konrad-kruczynski, I will add a test for a malformed binary.

**Comment by konrad-kruczynski** [comment]
@kweinmeister Hi, what's the current status?

**Comment by kweinmeister** [comment]
Sorry for the delay -- I haven't had time to add the additional unit test. Will try to look into this later.

**Comment by konrad-kruczynski** [comment]
Ok :)

**Comment by konrad-kruczynski** [comment]
I'm afraid I'll be closing this PR soon.

**Pull request closed without merging**
