### PR TITLE
Add support for Visual Studio 2017, .NET Core

### PR DESCRIPTION
**Pull request by qmfrederik**
This PR:
- Adds support for .NET Core & Visual Studio 2017 by upgrading to the new csproj file format and fixing a couple of compatibility issues
- Also (in a separate commit which is easy to drop if you don't like it) includes some of the MiscUtils code rather than linking it (as there is no MiscUtils for .NET Core)

### CODE REVIEW

**Comment by konrad-kruczynski** [comment]
Great idea! This week is rather hectic for me, but I'll try to analyse it as soon as possible.

**Comment by konrad-kruczynski** [comment]
I've finally got a chance to look at this. Am I correct that packages.json can now be removed? The other thing is that the test project located at https://github.com/konrad-kruczynski/elfsharp-tests should also be addressed. I guess that we could upgrade to nunit 3 at the same time, the test syntax is the same so it shouldn't be a problem. Would you like to make a PR on the test project with corresponding .NET core transformation? I can then look at it, handle nunit stuff etc.

**Comment by konrad-kruczynski** [comment]
Just as I mentioned in one of the active issues: I had to suspend development due to being really busy and I am finally starting to get back to the project. I'll try to look at your patches tomorrow. Respect for the patience - if you're still waiting ;)

**Comment by konrad-kruczynski** [comment]
OK, after quickly looking on the PR I think that because some time passed (my fault, naturally), we can go further and change framework to .net standard 2.0. I'll try to take care of this.

**Comment by qmfrederik** [comment]
@konrad-kruczynski Yes, netstandard2.0 will make life easier. I think it's safe to assume most people will abandon netstandard1.x fairly soon 😄 .

**Comment by qmfrederik** [comment]
So feel free to close this PR if you're doing netstandard2.0 work; I think it'll be a lot lighter compared to this PR.

**Comment by konrad-kruczynski** [comment]
Good point, closing then.

**Comment by konrad-kruczynski** [comment]
You can take a look at the issue #36. The project is already migrated to .NET Standard 2.0 (which was indeed a lot lighter), I also plan to merge main repo with the test one, so that only test binaries will be located externally. And also convert test project to .NET Standard during the process. New NuGet package is already available. I've used your files taken from the MiscUtil library, but actually plan to implement the functionality I need independently.

**Comment by qmfrederik** [comment]
@konrad-kruczynski Cool, thanks! Apologies for the late reply.

**Pull request closed without merging**
