### PR TITLE
Added .NET 4.5 and CI build with AppVeyor

### PR DESCRIPTION
**Pull request by bastianeicher**
This pull request adds .NET 4.5 builds with strong name signing.

It also adds AppVeyor configuration for automatic CI builds on Windows and Linux. This can be extended to automate pushing of NuGet packages.

You can see CI builds of my fork as an exmample here: https://ci.appveyor.com/project/bastianeicher/elfsharp

### CODE REVIEW

**Comment by konrad-kruczynski** [comment]
Finally had a time to look at this pull request, looks good to me. Also thanks for the appveyor hint.

**Comment by bastianeicher** [comment]
@konrad-kruczynski Could you perhaps publish a new release on NuGet that includes the .NET 4.5 target?

**Comment by konrad-kruczynski** [comment]
Sorry for the late reply. I thought that I’ve already done that. Now it should really be there :)

—
BR,
 Konrad

**Comment by bastianeicher** [comment]
No problem, thanks for the new build. :)

Happily in use in [here](https://github.com/0install/0install-dotnet/blob/master/src/Publish/EntryPoints/PosixBinary.cs).

**Pull request merged**
